import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  classifyPathV1,
  isReviewableRoleV1,
  looksGeneratedV1,
  type PathRoleV1,
} from "../../src/snapshot/path-classification.js";

describe("classifyPathV1", () => {
  it("classifies ordinary repository paths", () => {
    const cases: Array<[string, PathRoleV1]> = [
      ["src/provider/openrouter.ts", "SOURCE"],
      ["src/cart.js", "SOURCE"],
      ["scripts/deploy.sh", "SOURCE"],
      ["test/provider/openrouter.test.ts", "TEST"],
      ["src/cart.spec.ts", "TEST"],
      ["e2e/checkout.ts", "TEST"],
      ["package.json", "CONFIG"],
      ["tsconfig.json", "CONFIG"],
      ["deploy/values.yaml", "CONFIG"],
      ["docs/architecture.md", "DOCUMENTATION"],
      ["README.md", "DOCUMENTATION"],
      ["package-lock.json", "GENERATED"],
      ["pnpm-lock.yaml", "GENERATED"],
      ["dist/src/cli.js", "GENERATED"],
      ["src/vendor/thing.js", "GENERATED"],
      ["assets/app.min.js", "GENERATED"],
      ["src/index.d.ts", "GENERATED"],
      ["__snapshots__/render.snap", "GENERATED"],
    ];
    for (const [path, expected] of cases) {
      assert.equal(classifyPathV1(path), expected, path);
    }
  });

  it("keeps steering files even though they are documentation", () => {
    for (const path of [
      "CLAUDE.md",
      "AGENTS.md",
      "CONTRIBUTING.md",
      ".cursorrules",
      ".github/copilot-instructions.md",
      ".claude/skills/review.md",
    ]) {
      assert.equal(classifyPathV1(path), "STEERING", path);
      assert.equal(isReviewableRoleV1(classifyPathV1(path)), true, path);
    }
  });

  it("lets .gitattributes outrank every heuristic", () => {
    assert.equal(
      classifyPathV1("src/api/client.ts", { attributes: { generated: true } }),
      "GENERATED",
    );
    assert.equal(
      classifyPathV1("src/api/client.ts", { attributes: { vendored: true } }),
      "GENERATED",
    );
    assert.equal(
      classifyPathV1("src/notes.ts", { attributes: { documentation: true } }),
      "DOCUMENTATION",
    );
  });

  it("lets an explicit override outrank .gitattributes", () => {
    const overrides = new Map<string, PathRoleV1>([["src/api/client.ts", "SOURCE"]]);
    assert.equal(
      classifyPathV1("src/api/client.ts", { attributes: { generated: true }, overrides }),
      "SOURCE",
    );
  });

  it("detects a generated marker inside an otherwise ordinary source path", () => {
    const bytes = new TextEncoder().encode(
      "// Code generated by protoc-gen-ts. DO NOT EDIT.\nexport const x = 1;\n",
    );
    assert.equal(classifyPathV1("src/api/messages.ts", { bytes }), "GENERATED");
    assert.equal(classifyPathV1("src/api/messages.ts"), "SOURCE");
  });

  it("does not mistake a steering file for generated because it says do not edit", () => {
    const bytes = new TextEncoder().encode("# AGENTS\n\nDO NOT EDIT this by hand.\n");
    assert.equal(classifyPathV1("AGENTS.md", { bytes }), "STEERING");
  });

  it("treats captured binary content as binary", () => {
    assert.equal(classifyPathV1("assets/logo.ts", { binary: true }), "BINARY");
    assert.equal(isReviewableRoleV1("BINARY"), false);
  });

  it("reviews source, tests, configuration and steering; skips documentation and generated", () => {
    assert.deepEqual(
      (
        ["SOURCE", "TEST", "CONFIG", "STEERING", "DOCUMENTATION", "GENERATED", "BINARY"] as const
      ).map((role) => [role, isReviewableRoleV1(role)]),
      [
        ["SOURCE", true],
        ["TEST", true],
        ["CONFIG", true],
        ["STEERING", true],
        ["DOCUMENTATION", false],
        ["GENERATED", false],
        ["BINARY", false],
      ],
    );
  });
});

describe("looksGeneratedV1", () => {
  it("accepts short source and rejects a long-lined bundle", () => {
    assert.equal(looksGeneratedV1(new TextEncoder().encode("const a = 1;\n".repeat(50))), false);
    const minified = new TextEncoder().encode(`${"a".repeat(60_000)}\n`);
    assert.equal(looksGeneratedV1(minified), true);
  });

  it("does not call a large well-formatted file generated", () => {
    const source = new TextEncoder().encode("const value = compute(input);\n".repeat(4_000));
    assert.ok(source.byteLength > 50_000);
    assert.equal(looksGeneratedV1(source), false);
  });
});
