/**
 * Assigns every changed path a role, so a review can spend its evidence budget on code.
 *
 * Classification is deterministic by construction. Capture proves the tree was stable by reading
 * it twice and requiring the two state digests to match, and every artifact identity is a digest
 * over captured content, so a classifier that could answer differently on two runs would break the
 * freeze, the race check, and final-stage resume.
 */

export type PathRoleV1 =
  | "SOURCE"
  | "TEST"
  | "CONFIG"
  | "DOCUMENTATION"
  | "STEERING"
  | "GENERATED"
  | "BINARY";

/** Attributes Git itself resolves for a path, already the project's own declaration of intent. */
export interface PathGitAttributesV1 {
  generated?: boolean;
  vendored?: boolean;
  documentation?: boolean;
}

/** Agent and contributor instruction files: documentation the review must still see. */
const STEERING_FILENAMES_V1 = new Set([
  "claude.md",
  "agents.md",
  "agent.md",
  "cursorrules",
  ".cursorrules",
  "copilot-instructions.md",
  "contributing.md",
  "conventions.md",
]);

const STEERING_PATH_PATTERNS_V1 = [
  /(^|\/)\.independent-reviewer\/rules\.md$/i,
  /(^|\/)\.claude\//i,
  /(^|\/)\.cursor\/rules\//i,
  /(^|\/)\.github\/copilot-instructions\.md$/i,
];

const GENERATED_FILENAMES_V1 = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "composer.lock",
  "gemfile.lock",
  "poetry.lock",
  "cargo.lock",
  "go.sum",
]);

const GENERATED_PATH_PATTERNS_V1 = [
  /(^|\/)(dist|build|out|coverage|__generated__|__snapshots__|node_modules|vendor)\//i,
  /\.min\.(js|css)$/i,
  /\.(map|snap)$/i,
  /\.(pb|generated)\.[a-z]+$/i,
  /\.d\.ts$/i,
];

const TEST_PATH_PATTERNS_V1 = [
  /(^|\/)(test|tests|spec|__tests__|e2e)\//i,
  /\.(test|spec)\.[a-z]+$/i,
];

const SOURCE_EXTENSIONS_V1 = new Set([
  "ts",
  "tsx",
  "mts",
  "cts",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "rb",
  "go",
  "rs",
  "java",
  "kt",
  "kts",
  "swift",
  "c",
  "h",
  "cc",
  "cpp",
  "hpp",
  "cs",
  "php",
  "scala",
  "sh",
  "bash",
  "sql",
  "vue",
  "svelte",
]);

const CONFIG_EXTENSIONS_V1 = new Set([
  "json",
  "yaml",
  "yml",
  "toml",
  "ini",
  "cfg",
  "conf",
  "properties",
  "env",
  "xml",
]);

const DOCUMENTATION_EXTENSIONS_V1 = new Set(["md", "markdown", "rst", "adoc", "txt"]);

/** Bytes scanned for a generated-file marker; codegen tools put theirs in the opening lines. */
const MARKER_SCAN_BYTES_V1 = 2048;
const GENERATED_MARKER_V1 = /@generated\b|\bDO NOT EDIT\b|Code generated by/i;
/** A minified bundle is a handful of enormous lines; source is many short ones. */
const MINIFIED_MINIMUM_BYTES_V1 = 50_000;
const MINIFIED_AVERAGE_LINE_BYTES_V1 = 500;

function fileName(path: string): string {
  return (path.split("/").pop() ?? path).toLowerCase();
}

function extensionOf(path: string): string {
  const name = fileName(path);
  const index = name.lastIndexOf(".");
  return index <= 0 ? "" : name.slice(index + 1);
}

function isSteering(path: string): boolean {
  return (
    STEERING_FILENAMES_V1.has(fileName(path)) ||
    STEERING_PATH_PATTERNS_V1.some((pattern) => pattern.test(path))
  );
}

/** Reports whether captured bytes carry a codegen marker or look mechanically minified. */
export function looksGeneratedV1(bytes: Uint8Array): boolean {
  const head = Buffer.from(
    bytes.subarray(0, Math.min(bytes.byteLength, MARKER_SCAN_BYTES_V1)),
  ).toString("utf8");
  if (GENERATED_MARKER_V1.test(head)) {
    return true;
  }
  if (bytes.byteLength < MINIFIED_MINIMUM_BYTES_V1) {
    return false;
  }
  let newlines = 0;
  for (const byte of bytes) {
    if (byte === 0x0a) newlines += 1;
  }
  return bytes.byteLength / (newlines + 1) > MINIFIED_AVERAGE_LINE_BYTES_V1;
}

export interface ClassifyPathOptionsV1 {
  /** Resolved `.gitattributes` values, which outrank every heuristic below them. */
  attributes?: PathGitAttributesV1;
  /** Captured bytes, when available, for marker and minification detection. */
  bytes?: Uint8Array;
  /** Kind already determined by capture; non-text content is never source. */
  binary?: boolean;
  /** Repository-relative paths the run explicitly forces to a role. */
  overrides?: ReadonlyMap<string, PathRoleV1>;
}

/**
 * Resolves one path's role.
 *
 * Precedence runs from the most authoritative signal to the least: an explicit run override, the
 * project's own `.gitattributes`, content markers, then path and extension conventions. Steering
 * files are checked before documentation so an instruction file is never dropped as prose.
 */
export function classifyPathV1(path: string, options: ClassifyPathOptionsV1 = {}): PathRoleV1 {
  const override = options.overrides?.get(path);
  if (override) {
    return override;
  }
  const attributes = options.attributes;
  if (attributes?.generated || attributes?.vendored) {
    return "GENERATED";
  }
  if (isSteering(path)) {
    return "STEERING";
  }
  if (attributes?.documentation) {
    return "DOCUMENTATION";
  }
  if (options.binary) {
    return "BINARY";
  }
  if (
    GENERATED_FILENAMES_V1.has(fileName(path)) ||
    GENERATED_PATH_PATTERNS_V1.some((pattern) => pattern.test(path))
  ) {
    return "GENERATED";
  }
  if (options.bytes && looksGeneratedV1(options.bytes)) {
    return "GENERATED";
  }
  const extension = extensionOf(path);
  if (DOCUMENTATION_EXTENSIONS_V1.has(extension)) {
    return "DOCUMENTATION";
  }
  if (SOURCE_EXTENSIONS_V1.has(extension)) {
    return TEST_PATH_PATTERNS_V1.some((pattern) => pattern.test(path)) ? "TEST" : "SOURCE";
  }
  if (CONFIG_EXTENSIONS_V1.has(extension)) {
    return "CONFIG";
  }
  return "DOCUMENTATION";
}

/** Roles whose content is review evidence. Everything else is recorded and not transmitted. */
const REVIEWABLE_ROLES_V1: ReadonlySet<PathRoleV1> = new Set<PathRoleV1>([
  "SOURCE",
  "TEST",
  "CONFIG",
  "STEERING",
]);

export function isReviewableRoleV1(role: PathRoleV1): boolean {
  return REVIEWABLE_ROLES_V1.has(role);
}
